apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: be222dd/docker-sprint-boot:tagVersion
      ports:
        - containerPort: 8080
